### ISSUE TITLE
Failed to load on MC 1.20.6

### ISSUE THREAD

**Issue by ShaneBeee** [gmitch215/SocketMC#12]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.20.6

### SocketMC Version

1.20.6-0.1.2

### Description

The mod fails to load

### Steps to Reproduce

- install mod (I have installed on Quilt via MultiMC)
- try run it
- fails

### Expected Behavior

To run! ;) 

### Actual Behavior

Here is the error in console
```
Failed to start Minecraft:
java.lang.RuntimeException: Failed to read accessWidener file from mod socketmc
Exiting with -1
	at org.quiltmc.loader.impl.transformer.TransformCacheGenerator.loadAccessWideners(TransformCacheGenerator.java:117)
	at org.quiltmc.loader.impl.transformer.TransformCacheGenerator.generate(TransformCacheGenerator.java:50)
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.writeTransformCache(TransformCacheManager.java:302)
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.createTransformCache(TransformCacheManager.java:275)
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.populateTransformBundle(TransformCacheManager.java:105)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:378)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:307)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at org.quiltmc.loader.impl.transformer.TransformCacheGenerator.loadAccessWideners(TransformCacheGenerator.java:115)
	... 15 more
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

**Comment by gmitch215** [comment]
I messed up the Modrinth automation process, so it's using the `dev` build that isn't remapped. I'll fix it manually.

The JAR available on the Releases page should work fine. I'll close this once I can verify that the Modrinth build is fixed.

**Comment by ShaneBeee** [comment]
I just re-downloaded from Modrinth, and it appears to be loading 👍🏻
